### ISSUE TITLE
asan config fails on macOS ARM because of --disable-elf-hack

### ISSUE THREAD

**Issue by Trikolon** [emilio/mozconfigs#5]
```
[~/src/moz/mozilla-unified]$ buildwith asan
MOZBUILD=/Users/pbz/.mozbuild
MOZCONFIGS=/Users/pbz/src/moz/mozconfigs/mozconfigs
mk_add_options AUTOCLOBBER=1
ac_add_options --enable-address-sanitizer
ac_add_options --disable-jemalloc
ac_add_options --disable-crashreporter
ac_add_options --disable-elf-hack
if [ -z $ARTIFACT_BUILD ] && [ ! -z $ANDROID_BUILD ]; then
  ANDROID_NDK_DIR=$(ls $MOZBUILD | grep '^android-ndk-')
  ac_add_options --with-android-ndk=$MOZBUILD/$ANDROID_NDK_DIR
fi

SCCACHE_PATH="$MOZBUILD/sccache/sccache"
if command -v cygpath >/dev/null; then
  SCCACHE_PATH="$(cygpath -w $SCCACHE_PATH)"
fi

if [ -z $ARTIFACT_BUILD ]; then
  if [ ! -z "$CC" ]; then
    if [ -z "$HOST_CC" ]; then
      export HOST_CC="$CC"
    fi
    if [ -z "$HOST_CXX" ]; then
      export HOST_CXX="$CXX"
    fi
  fi
  if [ -z $DISABLE_SCCACHE ]; then
    if [ -f "$SCCACHE_PATH" ]; then
      ac_add_options --with-ccache=$SCCACHE_PATH
    fi
  fi
  if [ -z $CROSS_BUILD ]; then
    if command -v mold >/dev/null; then
      ac_add_options --enable-linker=mold
    fi
  fi
fi
mk_add_options MOZ_OBJDIR=/Users/pbz/src/moz/mozilla-unified/obj-asan
 0:00.36 Using Python 3.11.7 from /Users/pbz/.mozbuild/srcdirs/mozilla-unified-8d27f296be75/_virtualenvs/build/bin/python
 0:00.36 Adding configure options from /Users/pbz/src/moz/mozilla-unified/.mozconfig
 0:00.36   --enable-address-sanitizer
 0:00.36   --disable-jemalloc
 0:00.36   --disable-crashreporter
 0:00.36   --disable-elf-hack
 0:00.36   --with-ccache=/Users/pbz/.mozbuild/sccache/sccache
 0:00.36   MOZCONFIGS=/Users/pbz/src/moz/mozconfigs/mozconfigs
 0:00.36   SCCACHE_PATH=/Users/pbz/.mozbuild/sccache/sccache
 0:00.36   MOZBUILD=/Users/pbz/.mozbuild
 0:00.36 checking for vcs source checkout... git
 0:00.37 checking for a shell... /bin/sh
 0:00.39 checking for host system type... aarch64-apple-darwin23.3.0
 0:00.39 checking for target system type... aarch64-apple-darwin23.3.0
 0:00.50 checking whether cross compiling... no
 0:00.54 Traceback (most recent call last):
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/configure.py", line 351, in <module>
 0:00.54     sys.exit(main(sys.argv))
 0:00.54              ^^^^^^^^^^^^^^
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/configure.py", line 141, in main
 0:00.54     sandbox.run()
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 522, in run
 0:00.54     self._value_for(option)
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 627, in _value_for
 0:00.54     return self._value_for_option(obj)
 0:00.54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/python/mozbuild/mozbuild/util.py", line 1054, in method_call
 0:00.54     cache[args] = self.func(instance, *args)
 0:00.54                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.54   File "/Users/pbz/src/moz/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 694, in _value_for_option
 0:00.54     raise InvalidOptionError(
 0:00.54 mozbuild.configure.options.InvalidOptionError: --disable-elf-hack is not available in this configuration
*** Fix above errors and then restart with "./mach build"
```

Removing the option `--disable-elf-hack` fixed it for me.

**Comment by emilio** [comment]
It might be that we don't need it anymore: https://bugzilla.mozilla.org/show_bug.cgi?id=1854047
